---
bind_server_zones:
  ffp:
    serial: 2024020404
    notify: "yes"
    allow_transfer_to:
      - "fdc0:ffee:a10::2:0:0"
      - "fdc0:ffee:a10::3:0:0"
    records:
      - name: "@"
        type: NS
        value: ns1.ffp.
      - name: "@"
        type: NS
        value: ns2.ffp.
      - name: "@"
        type: NS
        value: ns3.ffp.
      - name: ns1
        type: AAAA
        value: "fdc0:ffee:a10::1:0:0"
      - name: ns1
        type: AAAA
        value: "fdc0:ffee:a10:10:0:1::"
      - name: ns2
        type: AAAA
        value: "fdc0:ffee:a10::2:0:0"
      - name: ns2
        type: AAAA
        value: "fdc0:ffee:a10:10:0:2::"
      - name: ns3
        type: AAAA
        value: "fdc0:ffee:a10::3:0:0"
      - name: ns3
        type: AAAA
        value: "fdc0:ffee:a10:10:0:3::"
#      - name: speedtest
#        type: A
#        value: 10.22.0.1
#      - name: speedtest
#        type: A
#        value: 10.22.16.1
      - name: speedtest
        type: AAAA
        value: "fdc0:ffee:a10::1:0:0"
      - name: speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:1::"
#      - name: speedtest
#        type: A
#        value: 10.22.0.2
#      - name: speedtest
#        type: A
#        value: 10.22.16.2
      - name: speedtest
        type: AAAA
        value: "fdc0:ffee:a10::2:0:0"
      - name: speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:2::"
#      - name: speedtest
#        type: A
#        value: 10.22.0.3
#      - name: speedtest
#        type: A
#        value: 10.22.16.3
      - name: speedtest
        type: AAAA
        value: "fdc0:ffee:a10::3:0:0"
      - name: speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:3::"
      - name: ipv4.speedtest
        type: A
        value: 10.22.0.1
      - name: ipv4.speedtest
        type: A
        value: 10.22.16.1
      - name: ipv4.speedtest
        type: A
        value: 10.22.0.2
      - name: ipv4.speedtest
        type: A
        value: 10.22.16.2
      - name: ipv4.speedtest
        type: A
        value: 10.22.0.3
      - name: ipv4.speedtest
        type: A
        value: 10.22.16.3
      - name: ipv6.speedtest
        type: AAAA
        value: "fdc0:ffee:a10::1:0:0"
      - name: ipv6.speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:1::"
      - name: ipv6.speedtest
        type: AAAA
        value: "fdc0:ffee:a10::2:0:0"
      - name: ipv6.speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:2::"
      - name: ipv6.speedtest
        type: AAAA
        value: "fdc0:ffee:a10::3:0:0"
      - name: ipv6.speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:3::"
      - name: gw1-ipv6-backend.speedtest
        type: AAAA
        value: "fdc0:ffee:a10::1:0:0"
      - name: gw1-ipv6-backend.speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:1::"
      - name: gw1-ipv4-backend.speedtest
        type: A
        value: 10.22.0.1
      - name: gw1-ipv4-backend.speedtest
        type: A
        value: 10.22.16.1
      - name: gw2-ipv6-backend.speedtest
        type: AAAA
        value: "fdc0:ffee:a10::2:0:0"
      - name: gw2-ipv6-backend.speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:2::"
      - name: gw2-ipv4-backend.speedtest
        type: A
        value: 10.22.0.2
      - name: gw2-ipv4-backend.speedtest
        type: A
        value: 10.22.16.2
      - name: gw3-ipv6-backend.speedtest
        type: AAAA
        value: "fdc0:ffee:a10::3:0:0"
      - name: gw3-ipv6-backend.speedtest
        type: AAAA
        value: "fdc0:ffee:a10:10:0:3::"
      - name: gw3-ipv4-backend.speedtest
        type: A
        value: 10.22.0.3
      - name: gw3-ipv4-backend.speedtest
        type: A
        value: 10.22.16.3
      - name: speed
        type: CNAME
        value: speedtest.ffp.
