---
wireguard_client_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35323833306633366330613366393263363565346537343665333964626664336631653064633038
  3631643566623233633038616536613261643334363162320a333735626138613261363436363437
  65393965633136653035383631386139646438353638616364646432316464306631663761323862
  6361353432393932320a366335396366383663383862393936313363363962643762303738663132
  65656530613033353532323937313339643936616461306161323865343533373235633738333363
  3062333934316236336434636236366462353236343032316363
# de-ber-wg-001 (IPv6)
#wireguard_client_public_key: 0qSP0VxoIhEhRK+fAHVvmfRdjPs2DmmpOCNLFP/7cGw=
#wireguard_client_endpoint: "[2a03:1b20:b:f011::a01f]:51820"
# de-ber-wg-002 (IPv6)
#wireguard_client_public_key: 8ov1Ws0ut3ixWDh9Chp7/WLVn9qC6/WVHtcBcuWBlgo=
#wireguard_client_endpoint: "2a03:1b20:b:f011::a02f]:51820"
# de-ber-wg-003 (IPv6)
#wireguard_client_public_key: USrMatdHiCL5AKdVMpHuYgWuMiK/GHPwRB3Xx00FhU0=
#wireguard_client_endpoint: "[2a03:1b20:b:f011::a03f]:51820"
# de-ber-wg-004 (IPv6)
#wireguard_client_public_key: 6PchzRRxzeeHdNLyn3Nz0gmN7pUyjoZMpKmKzJRL4GM=
#wireguard_client_endpoint: "[2a03:1b20:b:f011::a04f]:51820"
# de-ber-wg-005 (IPv6)
#wireguard_client_public_key: I4Y7e8LrtBC/7DLpUgRd5k+IZk+whOFVAZgbSivoiBI=
#wireguard_client_endpoint: "[2a03:1b20:b:f011::a05f]:51820"
# de-ber-wg-006 (IPv6)
#wireguard_client_public_key: eprzkkkSbXCANngQDo305DIAvkKAnZaN71IpTNaOoTk=
#wireguard_client_endpoint: "[2a03:1b20:b:f011::a06f]:51820"
# de-dus-wg-001 (IPv6)
#wireguard_client_public_key: ku1NYeOAGbY65YL/JKZhrqVzDJKXQiVj9USXbfkOBA0=
#wireguard_client_endpoint: "[2a03:d9c0:3000::a20f]:51820"
# de-dus-wg-002 (IPv6)
#wireguard_client_public_key: TPAIPTgu9jIitgX1Bz5xMCZJ9pRRZTdtZEOIxArO0Hc=
#wireguard_client_endpoint: "[2a03:d9c0:3000::a21f]:51820"
# de-dus-wg-003 (IPv6)
#wireguard_client_public_key: XgSe9UwEV4JJNPPzFFOVYS6scMTL4DeNlwqBl32lDw0=
#wireguard_client_endpoint: "[2a03:d9c0:3000::a22f]:51820"
# de-fra-wg-003 (IPv6) 
#wireguard_client_public_key: vVQKs2TeTbdAvl3sH16UWLSESncXAj0oBaNuFIUkLVk=
#wireguard_client_endpoint: "[2a03:1b20:6:f011::f201]:51820"
# de-fra-wg-005 (IPv6)
#wireguard_client_public_key: tpobOO6t18CzHjOg0S3RlZJMxd2tz4+BnRYS7NrjTnM=
#wireguard_client_endpoint: "[2a03:1b20:6:f011::f401]:51820"
# de-fra-wg-006 (IPv6) 
#wireguard_client_public_key: nAF0wrLG2+avwQfqxnXhBGPUBCvc3QCqWKH4nK5PfEU=
#wireguard_client_endpoint: "[2a03:1b20:6:f011::f501]:51820"
# de-fra-wg-007 (IPv6)
#wireguard_client_public_key: mTmrSuXmTnIC9l2Ur3/QgodGrVEhhIE3pRwOHZpiYys=
#wireguard_client_endpoint: "[2a03:1b20:6:f011::f601]:51820"
# de-fra-wg-101 (IPv6) 
#wireguard_client_public_key: Voioje9Gfb7aTiK2/H6VyHFK1AFap1glIX0Z1EX2mRQ=
#wireguard_client_endpoint: "[2001:ac8:20:274::a99f]:51820"
# de-fra-wg-102 (IPv6)
#wireguard_client_public_key: ydXFN45/kROELJrF6id+uIrnS5DvTKSCkZDjfL9De2Q=
#wireguard_client_endpoint: "[2001:ac8:20:275::f001]:51820"
# de-fra-wg-103 (IPv6)
#wireguard_client_public_key: KkShcqgwbkX2A9n1hhST6qu+m3ldxdJ2Lx8Eiw6mdXw=
#wireguard_client_endpoint: "[2001:ac8:20:276::f001]:51820"
# de-fra-wg-104 (IPv6)
#wireguard_client_public_key: uKTC5oP/zfn6SSjayiXDDR9L82X0tGYJd5LVn5kzyCc=
#wireguard_client_endpoint: "[2001:ac8:20:277::f001]:51820"
# de-fra-wg-105 (IPv6)
#wireguard_client_public_key: Sttn2cr14dvIcCrE8qdlRGHXriqvTyvQWC7dzujH/iM=
#wireguard_client_endpoint: "[2001:ac8:20:269::f001]:51820"
# de-fra-wg-106 (IPv6)
#wireguard_client_public_key: 9ldhvN7r4xGZkGehbsNfYb5tpyTJ5KBb5B3TbxCwklw=
#wireguard_client_endpoint: "[2001:ac8:20:270::f001]:51820"
# de-fra-wg-301 (IPv6)
wireguard_client_public_key: dNKRyh2MkJGZdg9jyUJtf9w5GHjX3+/fYatg+xi9TUM=
wireguard_client_endpoint: "[2a07:fe00:1::a23f]:51820"
# de-fra-wg-302 (IPv6)
#wireguard_client_public_key: A3DbIgPycEJhJ1fQ4zzcajLOKTZsJMeawjdPQiWav20=
#wireguard_client_endpoint: "[2a07:fe00:1::a24f]:51820"
# de-fra-wg-303 (IPv6)
#wireguard_client_public_key: 2P+9SjwVCEnMDnBiYfZtQLq9p2S2TFhCM0xJBoevYk4=
#wireguard_client_endpoint: "[2a07:fe00:1::a25f]:51820"
# de-fra-wg-304 (IPv6)
#wireguard_client_public_key: VgNcwWy8MRhfEZY+XSisDM1ykX+uXlHQScOLqqGMLkc=
#wireguard_client_endpoint: "[2a07:fe00:1::a26f]:51820"
# de-fra-wg-401 (IPv6)
#wireguard_client_public_key: AbM8fnQWmmX6Nv0Tz68LigPbGkamJgNjxgzPfENOdXU=
#wireguard_client_endpoint: "[2a02:6ea0:c762:1::a35f]:51820"
# de-fra-wg-402 (IPv6)
#wireguard_client_public_key: 6/PBbPtoeWpJA+HZc9Iqg/PPQWD7mGVvZdwQlr1vtRk=
#wireguard_client_endpoint: "[2a02:6ea0:c762:2::a36f]:51820"
# de-fra-wg-403 (IPv6)
#wireguard_client_public_key: HWzSNMbQOQafkVp68B7aLRirhNJ6x5Wjw8/y7oUuHW0=
#wireguard_client_endpoint: "[2a02:6ea0:c762:3::a37f]:51820"
wireguard_client_addresses:
  - 10.68.153.219/32
  - fc00:bbbb:bbbb:bb01::5:99da/128
