---
librespeed_frontend_config:
  - name: "Gateway 1 (Intern, IPv4)"
    server: "https://speed4.gw1.int.ffp.name/"
    dlURL: "api/garbage.php"
    ulURL: "api/empty.php"
    pingURL: "api/empty.php"
    getIpURL: "api/getIP.php"
  - name: "Gateway 1 (Intern, IPv6)"
    server: "https://speed6.gw1.int.ffp.name/"
    dlURL: "api/garbage.php"
    ulURL: "api/empty.php"
    pingURL: "api/empty.php"
    getIpURL: "api/getIP.php"
  - name: "Gateway 2 (Intern, IPv4)"
    server: "https://speed4.gw2.int.ffp.name/"
    dlURL: "api/garbage.php"
    ulURL: "api/empty.php"
    pingURL: "api/empty.php"
    getIpURL: "api/getIP.php"
  - name: "Gateway 2 (Intern, IPv6)"
    server: "https://speed6.gw2.int.ffp.name/"
    dlURL: "api/garbage.php"
    ulURL: "api/empty.php"
    pingURL: "api/empty.php"
    getIpURL: "api/getIP.php"
  - name: "Gateway 3 (Intern, IPv4)"
    server: "https://speed4.gw3.int.ffp.name/"
    dlURL: "api/garbage.php"
    ulURL: "api/empty.php"
    pingURL: "api/empty.php"
    getIpURL: "api/getIP.php"
  - name: "Gateway 3 (Intern, IPv6)"
    server: "https://speed6.gw3.int.ffp.name/"
    dlURL: "api/garbage.php"
    ulURL: "api/empty.php"
    pingURL: "api/empty.php"
    getIpURL: "api/getIP.php"
  - name: "Frankfurt (Internet, IPv4)"
    server: "https://ipv4-backend.speedtest.ffp.oci.0xef.de/"
    dlURL: "garbage.php"
    ulURL: "empty.php"
    pingURL: "empty.php"
    getIpURL: "getIP.php"
  - name: "Frankfurt (Internet, IPv6)"
    server: "https://ipv6-backend.speedtest.ffp.oci.0xef.de/"
    dlURL: "garbage.php"
    ulURL: "empty.php"
    pingURL: "empty.php"
    getIpURL: "getIP.php"
