---
node_exporter_web_listen_address: "[::1]:9100"
node_exporter_enabled_collectors: []
node_exporter_disabled_collectors:
  - bcache
  - bonding
  - btrfs
  - dmi
  - fibrechannel
  - mdadm
  - nfs
  - nfsd
  - tapestats
  # - thermal
  # - thermal_zone
node_exporter_web_telemetry_path: "/metrics/node"
