$ANSIBLE_VAULT;1.1;AES256
63323638333939646366343734373531356566633432643630656435653939356563373539333233
3466316230613535303734313464626138313330383530350a373936653531343838303636353934
63386563666239613233663730336438363261303361373466383963356262373761303332636635
3231323635366362640a356462393635356263663762613838376639303739333436376435373037
32663132303466633430623764323730643566663432303366336536373838326637323663373861
33306237653337373664646530396231623431613230366630653032383633313437336537306436
36326237663763663538356162663937346339356130656138323130636531643662313832313361
64663933376532303737623130366430653465336538383162633032393035313738653936313938
30333964393535643063653231636663303732313837346236636631613335343838353862376334
62636631363530643035656466343361346236653864623564376337316464666166326530393164
31366632373839663461386337316339323062663738636362646561313637313231393861633837
36626664333634333037366361636336373665303233653136326162313238383665633430303538
64616139333261663630343532336231376364346234353434303234656661316432663835313533
36333563653665636331623732326164366363393231383634383664303362643233653266313265
643065313837373535373366653634356266
