galaxy_info:
  author: Hannes Fuchs
  description: Install / Remove packages

  issue_tracker_url: https://github.com/Freifunk-Potsdam/ansible-collection-gluon/issues

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: CC0-1.0

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - packages
    - system
    - administration

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
